# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/codalia/membership/models/category/fields.yaml

# Model Class name
modelClass: Codalia\Membership\Models\Category

# Default redirect location
defaultRedirect: codalia/membership/categories

# Create page
create:
    title: Create Category
    redirect: codalia/membership/categories/update/:id
    redirectClose: codalia/membership/categories

# Update page
update:
    title: Edit Category
    redirect: codalia/membership/categories
    redirectClose: codalia/membership/categories

# Preview page
preview:
    title: Preview Category
