# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: codalia.membership::lang.membership.members

# Model Form Field configuration
form: $/codalia/membership/models/member/fields.yaml

# Model Class name
modelClass: Codalia\Membership\Models\Member

# Default redirect location
defaultRedirect: codalia/membership/members

# Create page
create:
    title: codalia.membership::lang.action.create
    redirect: codalia/membership/members/update/:id
    redirectClose: codalia/membership/members

# Update page
update:
    title: codalia.membership::lang.action.edit
    redirect: codalia/membership/members/update/:id
    redirectClose: codalia/membership/members

# Preview page
preview:
    title: Preview Member
