# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    status:
        label: codalia.journal::lang.articles.filter_status
        type: group
        conditions: status in (:filtered)
        options:
            pending: codalia.membership::lang.status.pending
            refused: codalia.membership::lang.status.refused
            pending_subscription: codalia.membership::lang.status.pending_subscription
            cancelled: codalia.membership::lang.status.cancelled
            member: codalia.membership::lang.status.member
            pending_renewal: codalia.membership::lang.status.pending_renewal
            revoked: codalia.membership::lang.status.revoked

    category:
        # Filter name
        label: codalia.membership::lang.attribute.category
        # Model Class name
        modelClass: Codalia\Membership\Models\Category
        # Model attribute to display for the name
        nameFrom: name
        # Apply query scope
        scope: FilterCategories
